### ISSUE TITLE
Pwm oscillator

### ISSUE THREAD

**Issue by jpcima** [jpcima/string-machine#13]
It's available in `pwm` branch.

demo: [pwm.flac.gz](https://github.com/jpcima/string-machine/files/3831414/pwm.flac.gz)
PWM off vs PWM 100% 0.6Hz

cc @farvardin if you are interested to review the feature

**Comment by farvardin** [comment]
It works fine! It's a powerful addition...

**Comment by jpcima** [comment]
The PWM feature is now part of software, thank you for feedback.
