### ISSUE TITLE
Raspberry pi build fail

### ISSUE THREAD

**Issue by Baggypants** [jpcima/string-machine#15]
cannot compile due to compile options -msse -msse2 

```
root@zynthian:/media/usb/Develop/string-machine# make
make -C dpf/dgl ../build/libdgl-cairo.a
make[1]: Entering directory '/media/usb0/Develop/string-machine/dpf/dgl'
Compiling src/Application.cpp
g++: error: unrecognized command line option ‘-msse’; did you mean ‘-fdse’?
g++: error: unrecognized command line option ‘-msse2’
```

**Comment by jpcima** [comment]
Hi it's because of the dpf submodule which is not able to detect the processor in this version, and assumes Intel.

Solutions are:
- update dpf submodule manually, where I fixed this detection upstream (which I will do in a moment)
- or, pass `NOOPT=true` on the make line to skip SSE flags, the same as MOD Devices uses which is ARM-based

**Comment by Baggypants** [comment]
updating dpf now continues with the compile!

**Comment by Baggypants** [comment]
compiles perfectly and plays on an rpi4 Audio clip here: https://discourse.zynthian.org/t/any-lv2-arp-solina-roland-rs-type-string-machines/3627/6?u=baggypants

**Comment by jpcima** [comment]
very nice, I'm actually curious of the CPU usage on these machines.

Do you know if performance significantly better when BBD delay type is switched to digital?

(there is some room for improving at these step, which I have not yet really explored)

**Comment by Baggypants** [comment]
Not hugely, seemed around 29% CPU for digital chorus model vs 32%CPU for BBD chorus model. using top as a reference, playing 29 notes simultaneously.

**Comment by Baggypants** [comment]
Turning off the compiled in chorus and using the stereo chorus lv2 shows it uses 4.5% digital 6.6% BBD. With the added advantage it will run on a separate core of the pi4 as it' a multi-core cpu, the pi3 only has 1 core.

**Comment by jpcima** [comment]
Ok noted, a polyphony of 29 is a lot to process, and CPU workload is going to act proportional.

Right now this program has **unlimited** polyphony and it can be a problem.
There is not a setting to enable a limit.

A thing which I think is not too well handled, it's notes continuing to be released a too long time after reaching silence, and I should make it shorter. It causes computation of more voices than truly are needed I think.
