### ISSUE TITLE
Zynthian: Push any key followed by the key one octave down, the second note doesn't play.  

### ISSUE THREAD

**Issue by MrDham** [jpcima/string-machine#22]
Observed on Zynthian. 

1. I push C3 and don't release it -> I hear C3
2. I push any other key than C2. -> I hear the two notes
3. I release the second key  -> I still hear C3 
4. I push C2 -> I hear C3 only

**Comment by jpcima** [comment]
Hi, I've been told of some MIDI problems with notes on Zynthian devices.
I had no luck at reproducing such problems unfortunately, and not any better with this one.

- do you have the very latest ?
- does it happen regardless of the choice of preset ?

**Comment by MrDham** [comment]
Hi,

Effectivelly, I read the dicussion on Zynthian forum and also saw bug #18. 
I thought that this symptom could be related to the same problem. 
Anyway, I submitted this bug because the issue seems slightly different .

To be sure, I just updated the string machine on the zynthian but it still happens regardless of the choice of preset. 

I hope it will help. 
(Great synth anyway :-) )

**Comment by jpcima** [comment]
These problem reports are very puzzling. I don't have a beginning of an idea, for now.
Did you have the polyphony setting set at 3 or more ?

What about just a C2+C3 chord ? it's the fault of just this pair of keys, or the entire sequence?

**Comment by MrDham** [comment]
Hi, 

I made some complementary test. 

I checked with another LV2 synth from the zynthian collection, the problem was there too. 
So this problem is not at your side ! 
(It is somewhere between the man in front of the keyboard and the zynthian)

I am very sorry for disturbing you with it.

**Comment by MrDham** [comment]
The problem is a very strange bug related to transposition that I just discovered in my 30 year old keyboard. You can definitively ignore this bug.

**Comment by jpcima** [comment]
Ah great, it's a relief to know.
It's no problem, don't worry about it.
