### ISSUE TITLE
Infinite loop?

### ISSUE THREAD

**Issue by trebmuh** [jpcima/string-machine#27]
https://github.com/jpcima/string-machine/blob/master/tests/string-osc/sources/string-machine

**Comment by jpcima** [comment]
It's as intended.
Does this create any problems on your side?

**Comment by trebmuh** [comment]
It uses to, because of a bug with my D.E. (MATE) _(see [this thread for more info](https://lists.debian.org/debian-user-french/2020/09/msg00036.html))_
But now that I have a workaround for this bug, it doesn't anymore.
Closing then.
