### ISSUE TITLE
No install target

### ISSUE THREAD

**Issue by yurivict** [jpcima/string-machine#4]
Please see how the Arch Linux installs it manually: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=string-machine-git

**Comment by jpcima** [comment]
Hi, this was implemented in 286bf56.

Following variables are provided to customize the preferred location as necessary.
```
DESTDIR ?=
PREFIX ?= /usr
BINDIR ?= $(PREFIX)/bin
LIBDIR ?= $(PREFIX)/lib
LV2DIR ?= $(LIBDIR)/lv2
VSTDIR ?= $(LIBDIR)/vst
```
